// MyPlugin file generated by Kari. Feel free to change it or remove this message.
using System.Threading.Tasks;
using Kari.GeneratorCore.Workflow;
using Kari.Utils;

namespace Kari.Plugins.MyPlugin
{
    // The plugin interface to Kari.
    // Kari will call methods of this class to analyze and then generate code.
    public class MyPluginAdministrator : IAdministrator
    {
        public MyPluginAnalyzer[] _analyzers;
        
        // Called after all of the projects have been loaded
        public void Initialize()
        {
            AdministratorHelpers.Initialize(ref _analyzers);
            var logger = new NamedLogger("MyPlugin");
            MyPluginSymbols.Initialize(logger);
        }
        
        // Called when it is time to find ("collect") the types and methods you need to analyze.
        // At this stage, info objects are created and stored, 
        // containing the final data needed to generate the output.
        public Task Collect()
        {
            return AdministratorHelpers.CollectAsync(_analyzers);
        }
        
        // Called to generate code. The name of the files can be anything.
        public Task Generate()
        {
            return Task.WhenAll(
                AdministratorHelpers.GenerateAsync(_analyzers, "MyPlugin.cs"),
                // Write the attributes to an acessible file.
                AdministratorHelpers.AddCodeStringAsync(
                    MasterEnvironment.Instance.CommonPseudoProject,
                    "MyPluginAnnotations.cs", "MyPlugin", GetAnnotations())
            );
        }
        
        public string GetAnnotations() => DummyMyPluginAnnotations.Text;
    }
}
