// Autogenerated from RelevantSymbols.tt

namespace Kari.GeneratorCore.CodeAnalysis
{
	using System;
	using Microsoft.CodeAnalysis;
	using Kari.Shared;

	public partial class RelevantSymbols
	{
		public AttributeSymbolWrapper<KariTestAttribute> KariTestAttributeWrapper;
		
		public void Init(Compilation compilation, Action<string> logger)
		{
			KariTestAttributeWrapper.Init(compilation);
		}
	}
}